name: one_dollar_unistroke_recognizer
description: The $1 Unistroke Recognizer, a 2D single-stroke recognizer. This is a Dart port of the original JavaScript implementation.
version: 0.4.2
homepage: https://adil192.github.io/one_dollar_unistroke_recognizer/
repository: https://github.com/adil192/one_dollar_unistroke_recognizer
issue_tracker: https://github.com/adil192/one_dollar_unistroke_recognizer/issues

topics:
  - one-dollar
  - unistrokes
  - shape-recognition
  - gesture-recognition

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
